### ISSUE TITLE
Validating but getting error: stepValidate.then.catch

### ISSUE THREAD

**Issue by BertBR** [arb/celebrate#186]
- `node` version - 10.12.0
- `celebrate` version - 12.2.0
- `joi` version (via `npm ls --depth=0 | grep joi`) - 17.2.1

My `joi` schema looks like this:

```js
return celebrate(
      {
      body: Joi.object().keys(
          {
              title: Joi.string().max(255).required(),
          }
       )

```
The validation is working but i'm getting something "more" about **stepValidate**.

The issue I am having with `celebrate` is:

I'm getting this return as response:

```
>  Error: "title" is required
>      at stepValidate.then.catch (/Users/bert/Documents/Projects/NodeJS/myProject/firebase/functions/node_modules/celebrate/lib/index.js:104:13)
>      at process._tickCallback (internal/process/next_tick.js:68:7)
```

**Comment by BertBR** [comment]
Solved with router.use(errors());
